version: '3.8'

services:
  db:
    image: postgres:15
    container_name: converge-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: buddy
    ports:
        - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: converge-backend
    build: .
    depends_on:
        - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/buddy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234


volumes:
  pgdata:

